apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: hello-kubernetes
  namespace: hello-kubernetes
spec:
  ingress:
    ingressClassName: nginx
    rules:
      - host: kcdporto.demo.diegomarques.dev
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-kubernetes-hello-kubernetes
                port:
                  name: http
  strategy:
    primaryGeoTag: aws-eastus1
    type: failover
