apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-kubernetes
  namespace: flux-system
spec:
  releaseName: hello-kubernetes
  targetNamespace: hello-kubernetes
  interval: 1h0m0s
  chart:
    spec:
      chart: gitops/apps/hello-kubernetes/chart
      sourceRef:
        kind: GitRepository
        name: gitops
        namespace: flux-system
  values: 
    message: "Welcome from provider ${cloud_provider}"     
    service:
      type: "ClusterIP" 