apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8gb
  namespace: flux-system
spec:
  releaseName: k8gb
  targetNamespace: k8gb
  interval: 1h0m0s
  chart:
    spec:
      chart: k8gb
      sourceRef:
        kind: HelmRepository
        name: k8gb
        namespace: flux-system
  values:
    k8gb:
      dnsZone: "demo.diegomarques.dev"
      edgeDNSZone: "diegomarques.dev"
      edgeDNSServers:
          # -- use these DNS server as a main resolver to enable cross k8gb DNS based communication
          - "1.1.1.1"
          - "8.8.8.8"
      clusterGeoTag: "${geoTag}"
      extGslbClustersGeoTags: "${geoPairTag}"
      reconcileRequeueSeconds: 10

    route53:
      enabled: true
      hostedZoneID: Z01192663NI0F34O48853
      secret: external-dns
      irsaRole: "arn:aws:iam::024848453634:role/external-dns-k8gb"

    coredns:
      serviceType: LoadBalancer
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: 30219