apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: common
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: gitops/cluster-config/common
  interval: 30s
  retryInterval: 60s
  timeout: 600s
  force: true
  prune: true
  postBuild:
    substitute:
      clusterName: "k8gb-kcdporto-aws"
      geoTag: "aws-useast1"
      geoPairTag: "azure-northeurope"